### ISSUE TITLE
Error putting external IP address.

### ISSUE THREAD

**Issue by jeckestripador** [opentibiabr/login-server#13]
When editing the IP in the .env file, for an external IP, it stops running and closes.

**executable log:**
Aug 31 23:41:16.878←[36m [INFO] ←[0mWelcome to OTBR Login Server
Aug 31 23:41:16.897←[36m [INFO] ←[0mLoading configurations...
Aug 31 23:41:16.898←[36m [INFO] ←[0mStarting gRPC server...
Aug 31 23:41:16.898←[36m [INFO] ←[0mStarting api server...
Aug 31 23:41:16.900←[31m [ERRO] ←[0mlisten tcp 177.67.205.10:80: bind: O endereço solicitado não é válido no contexto.
Aug 31 23:41:16.900←[33m [WARN] ←[0mServer api is gone...
Aug 31 23:41:16.900←[31m [ERRO] ←[0mlisten tcp 177.67.205.10:9090: bind: O endereço solicitado não é válido no contexto.
Aug 31 23:41:16.900←[33m [WARN] ←[0mServer gRPC is gone...

.**env file:**
MYSQL_DBNAME=*******
MYSQL_HOST=localhost
MYSQL_PORT=3306
MYSQL_USER=*******
MYSQL_PASS=********
ENV_LOG_LEVEL=debug
LOGIN_IP=177.67.205.10
LOGIN_HTTP_PORT=80
LOGIN_GRPC_PORT=9090
RATE_LIMITER_BURST=5
RATE_LIMITER_RATE=2
SERVER_IP=177.67.205.10
SERVER_NAME=Teste
SERVER_PORT=7171
VOCATIONS=None,Sorcerer,Druid,Paladin,Knight,Master Sorcerer,Elder Druid,Royal Paladin,Elite Knight
SERVER_LOCATION=BRA

**Comment by lgrossi** [comment]
This is not a problem of the server, but most probably of the ip you've selected or the configurations you've used. It works fine in multiple setups I've tested (cloud, local, local with docker).
